### ISSUE TITLE
Empty tag does not work in some browser

### ISSUE THREAD

**Issue by ruchern** [krestaino/weather-vue#29]
My IDE, PHPStorm is throwing the following error for closing tags.

<img width="1280" alt="screen shot 2017-06-11 at 10 48 18 am" src="https://user-images.githubusercontent.com/10343662/27007850-9715cdec-4e93-11e7-8831-72789f9687f5.png">

**Comment by ruchern** [comment]
@krestaino At the same time, I would like to apologise that my IDE may have screwed up with the indentation of the project by a bit. I did set the IDE to use the `.eslint.rc` file to format.

**Comment by krestaino** [comment]
@ruchern No worries about the indentation. I cleaned it up in 45aa8f8.

I'm following Google's style guide for this project.

https://google.github.io/styleguide/htmlcssguide.html
https://google.github.io/styleguide/jsguide.html

Regarding you IDE, I'm not too familiar with `.editorconfig`, but should the IDE use that file instead of `.eslintrc.js`?

**Comment by ruchern** [comment]
@krestaino I think we should follow `.eslintrc.js` for indentation.

**Comment by krestaino** [comment]
Hmm. [.editorconfig](https://github.com/krestaino/weather-vue/blob/master/) already specifies indentation. I'm not too familiar with `.editorconfig`, but according to its [docs](http://editorconfig.org/), it seems that file is responsible for code style.

Isn't `.eslintrc.js` just used for JavaScript linting?
